### ISSUE TITLE
is it possible to route a certain percentage of requests to certain apps ?

### ISSUE THREAD

**Issue by MathieuDerelle** [dmytrostriletskyi/heroku-load-balancer#11]
let's say I wanna balance between two apps, is it possible to have a 90% / 10% balance ?
(or is your code always balancing at equal rate 50 / 50 ?)

**Comment by dmytrostriletskyi** [comment]
Hi, @MathieuDerelle,

sorry for my late response. The project is based on the Nginx project. So, it's possible eventually. 

What you need to adjust is weights — http://nginx.org/en/docs/http/load_balancing.html#nginx_weighted_load_balancing
You can fork the project and adjust the config file — https://github.com/dmytrostriletskyi/heroku-load-balancer/blob/develop/src/constants.py
