### ISSUE TITLE
301 redirects do not work

### ISSUE THREAD

**Issue by FabioFleitas** [dmytrostriletskyi/heroku-load-balancer#8]
It looks like redirects do not work as they redirect you to `http://main:8001/login/?next=/dashboard/` for example

**Comment by FabioFleitas** [comment]
@dmytrostriletskyi we found a solution to this. Basically it required updating to `ubuntu:18.04` so that you can use at least nginx `1.11.x` version then setting the following as part of the config:
```
absolute_redirect off;
port_in_redirect off;
```

I can put together a PR if you'd like. We forked this and added a few other enhancements, feel free to checkout here: https://github.com/dmytrostriletskyi/heroku-load-balancer/compare/develop...Tesorio:develop

**Comment by dmytrostriletskyi** [comment]
@FabioFleitas, hi! 

I am glad you found the project useful. It'd be great if you create a pull request with your changes! :)

Thank you.
